# Generated by Django 4.0 on 2023-05-09 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=200)),
                ('pattern', models.TextField()),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'vihoapp_patterns',
            },
        ),
        migrations.CreateModel(
            name='DataProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data_source', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DOING', 'DOING'), ('DONE', 'DONE')], default='PENDING', max_length=255)),
                ('result', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vihoapp_profile',
            },
        ),
    ]
