# Generated by Django 4.0 on 2023-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprofile',
            name='profile_time',
            field=models.IntegerField(default=0),
        ),
    ]
