# Generated by Django 4.0 on 2023-06-28 02:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_profile', '0002_dataprofile_profile_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprofile',
            name='profile_time',
        ),
        migrations.RemoveField(
            model_name='dataprofile',
            name='result',
        ),
        migrations.AddField(
            model_name='dataprofile',
            name='data_source_output',
            field=models.CharField(default='output', max_length=255),
        ),
        migrations.CreateModel(
            name='DataProfileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.IntegerField()),
                ('profile_result', models.TextField()),
                ('profile_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('profile_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vihoapp_profile_history',
            },
        ),
    ]
