# Generated by Django 4.0 on 2023-05-17 06:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=50)),
                ('vat_tax_id', models.CharField(max_length=50, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('details', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('size', models.CharField(default=0, max_length=250)),
                ('datacount', models.CharField(default=0, max_length=250)),
                ('contentType', models.CharField(max_length=250, null=True)),
                ('contentTypeExtra', models.CharField(max_length=250, null=True)),
                ('charset', models.CharField(max_length=250, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('columnData', models.TextField(blank=True, null=True)),
                ('original_name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 5, 17, 6, 59, 42, 904866, tzinfo=utc))),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='vihoapp.project', verbose_name='id')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='id')),
            ],
        ),
    ]
