# Generated by Django 4.0 on 2023-05-17 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 17, 7, 1, 59, 174981, tzinfo=utc)),
        ),
    ]
