<<<<<<< HEAD
# Generated by Django 4.0 on 2023-07-17 22:53
=======
# Generated by Django 4.0 on 2023-07-21 10:22
>>>>>>> master

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0038_alter_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 22, 52, 58, 244221, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 10, 22, 44, 611304, tzinfo=utc)),
>>>>>>> master
        ),
    ]
