<<<<<<< HEAD
# Generated by Django 4.0 on 2023-07-18 20:30
=======
# Generated by Django 4.0 on 2023-07-21 10:31
>>>>>>> master

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0039_alter_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 20, 30, 17, 534698, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 10, 31, 42, 822883, tzinfo=utc)),
>>>>>>> master
        ),
    ]
