<<<<<<< HEAD
# Generated by Django 4.0 on 2023-07-18 20:50
=======
# Generated by Django 4.0 on 2023-07-21 10:34
>>>>>>> master

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0040_alter_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 20, 50, 42, 555684, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 10, 34, 6, 678977, tzinfo=utc)),
>>>>>>> master
        ),
    ]
