<<<<<<< HEAD
# Generated by Django 4.0 on 2023-07-18 21:58
=======
# Generated by Django 4.0 on 2023-07-21 10:51
>>>>>>> master

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0042_alter_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 21, 58, 27, 901508, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 10, 51, 17, 192483, tzinfo=utc)),
>>>>>>> master
        ),
    ]
