<<<<<<< HEAD
# Generated by Django 4.0 on 2023-07-18 22:46
=======
# Generated by Django 4.0 on 2023-07-21 11:05
>>>>>>> master

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0043_alter_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 22, 46, 4, 971780, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 11, 4, 54, 977110, tzinfo=utc)),
>>>>>>> master
        ),
    ]
