<<<<<<< HEAD
# Generated by Django 4.0 on 2023-07-19 00:04
=======
# Generated by Django 4.0 on 2023-07-21 11:14
>>>>>>> master

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0044_alter_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 0, 4, 47, 981493, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 11, 14, 27, 695876, tzinfo=utc)),
>>>>>>> master
        ),
    ]
