<<<<<<< HEAD
# Generated by Django 4.0 on 2023-07-19 09:11
=======
# Generated by Django 4.0 on 2023-07-21 11:17
>>>>>>> master

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0045_alter_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 11, 47, 19448, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 11, 17, 31, 717344, tzinfo=utc)),
>>>>>>> master
        ),
    ]
