<<<<<<< HEAD
# Generated by Django 4.0 on 2023-07-19 09:18
=======
# Generated by Django 4.0 on 2023-07-21 20:52
>>>>>>> master

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vihoapp', '0046_alter_datafile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='created',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 9, 18, 37, 318957, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 20, 52, 48, 834244, tzinfo=utc)),
>>>>>>> master
        ),
    ]
