# Generated by Django 4.0 on 2023-05-17 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'vihoapp_category',
            },
        ),
        migrations.CreateModel(
            name='MappingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senzing_map_name', models.CharField(max_length=250)),
                ('display_name', models.CharField(max_length=250)),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mapping.category', verbose_name='id')),
            ],
            options={
                'db_table': 'vihoapp_mappinglist',
            },
        ),
    ]
