# Generated by Django 4.0 on 2023-05-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mappinglist',
            old_name='category_id',
            new_name='category',
        ),
    ]
