# Generated by Django 4.0 on 2023-05-22 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapping', '0003_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingRecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('datasource', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mapping.datasource', verbose_name='id')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='id')),
            ],
            options={
                'db_table': 'vihoapp_mappingrecode',
            },
        ),
    ]
