# Generated by Django 4.0 on 2023-05-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_mappingrecode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mappingrecode',
            table='vihoapp_mappingrecord',
        ),
    ]
