# Generated by Django 4.0 on 2023-05-22 18:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapping', '0005_alter_mappingrecode_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MappingRecode',
            new_name='MappingRecord',
        ),
    ]
