# Generated by Django 4.0 on 2023-07-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.JSONField()),
            ],
            options={
                'verbose_name': 'Customer Master',
            },
        ),
        migrations.CreateModel(
            name='exceldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('Industry', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchdata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NewProsectRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data2', models.JSONField()),
            ],
            options={
                'verbose_name': 'New Prospect Records',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relationships', to='apis.customermaster')),
                ('to_data', models.ManyToManyField(related_name='to_relationships', to='apis.CustomerMaster')),
            ],
        ),
    ]
